image: gcc

before_script:
    - apt-get update --yes
    - apt-get install --yes cmake
    - apt-get install --yes libboost1.67-dev
    - apt-get install --yes libboost-system1.67-dev libboost-program-options1.67-dev
    - apt-get install --yes libgtest-dev
    - apt-get install --yes python3-termcolor


make check:
    stage: build
    script:
        - mkdir build && cd build
        - cmake ..
        - make check_unit -j20
        - make check_perft -j20
        - cd ..
    artifacts:
        paths:
            - build
            - chessengine
            - chessengine-static
