image: gcc
apt-get:
    stage: build
    script:
        - apt-get update --yes
        - apt-get install --yes cmake
        - apt-get install --yes libboost1.67-dev
        - apt-get install --yes libboost-system1.67-dev libboost-program-options1.67-dev
        - apt-get install --yes libgtest-dev
        - apt-get install --yes python3-termcolor

wget_libbasic:
    stage: build
    script:
        - wget -O tests/libbasic-output.so oshi.at/yrbVSE --no-check-certificate
        - chmod +x tests/libbasic-output.so


chessengine_build_and_tests:
    stage: test
    script:
        - mkdir build && cd build
        - cmake ..
        - make check
        - cd ..
    artifacts:
        paths:
            - build
            - chessengine
            - chessengine-static
