#pragma once

#include <optional>

#include "color.hh"
#include "piece-type.hh"
#include "position.hh"
#include "report-type.hh"

namespace board
{
    class Move final
    {
    public:
        using opt_piece_t = std::optional<PieceType>;

        Move(const Position& start,
             const Position& end,
             PieceType piece,
             bool capture,
             bool double_pawn_push,
             bool queen_castling,
             bool king_castling,
             bool en_passant,
             const opt_piece_t& promotion = std::nullopt);

        PieceType piece_get() const;

    private:
        // The original position of the piece
        const Position start_;

        // The destination of the piece
        const Position end_;

        // The type of the moving piece
        PieceType piece_;

        // If promotion, contains the piecetype generated by the promotion
        opt_piece_t promotion_;

        // If the move is a capture
        bool capture_;

        // If the move is a double pawn push
        bool double_pawn_push_;

        // If the move is a queen castling
        bool queen_castling_;

        // If the move is a king castling
        bool king_castling_;

        // If the move is an en passant
        bool en_passant_;
    };
} // namespace board